export default function Head() {
    return (
        <>
            <meta content='width=device-width, initial-scale=1' name='viewport' />
            <link rel='icon' href='/favicon.ico' />

            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-Black.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-Black-Italic.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-ExtraBold.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-ExtraBold-Italic.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-Bold.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-Bold-Italic.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-SemiBold.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-SemiBold-Italic.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-Medium.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-Medium-Italic.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-Regular.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-Regular-Italic.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-Light.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-Light-Italic.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-ExtraLight.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-ExtraLight-Italic.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-Thin.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
            <link
                rel='preload'
                href='/fonts/metropolis/Metropolis-Thin-Italic.otf'
                as='font'
                type='font/otf'
                crossOrigin='anonymous'
            />
        </>
    )
}
